#!/usr/bin/env python3
from telegram import Bot
import asyncio
import cloudscraper
import os

token = os.environ.get("TG_TOKEN")
channel = os.environ.get("TG_CHANNEL")

API_HEADERS = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
    "X-API-Key": "jfsTOgOL23CN2G8Y",
}
API_URL = "https://mobileapi.x-kom.pl/api/v1/xkom/hotShots/current?onlyHeader=true"

def get_hot_shot():
    requests = cloudscraper.create_scraper()
    response = requests.get(url=API_URL, headers=API_HEADERS).json()
    hot_shot_info = {
        "name": response['PromotionName'],
        "price": response['Price'],
        "old_price": response['OldPrice'],
        "link": f"https://www.x-kom.pl/goracy_strzal/{response['Id']}",
        "photo_url": response['PromotionPhoto']['Url'],
    }
    return hot_shot_info

async def main():
    bot = Bot(token)
    hot_shot_data = get_hot_shot()
    description = (
        f"Item: {hot_shot_data['name']}\n"
        f"Cena: {hot_shot_data['price']} PLN\n"
        f"Stara cena: {hot_shot_data['old_price']} PLN\n"
        f"Link: {hot_shot_data['link']}"
    )
    try:
        await bot.send_photo(chat_id=channel, photo=hot_shot_data['photo_url'], caption=description)
    except Exception as e:
        await bot.send_message(chat_id=channel, text=description)

if __name__ == '__main__':
    asyncio.run(main())
